server:
  address: 0.0.0.0
  port: 8080

ai:
  server:
    url: http://127.0.0.1:8000

spring:
  profiles:
    include:
      - aws
      - credentials

  datasource:
    url: jdbc:mysql://localhost:3306/tindy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  config:
    import: optional:classpath:application-credentials.yml
